server:
  port: 9001

spring:
  profiles:
    active:
      dev
---
spring:
  jackson:
    time-zone: Europe/Bucharest
  profiles:
    dev
  jpa:
    properties:
      hibernate:
        default_schema: blog
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:blog;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;Mode=PostgreSQL;DATABASE_TO_UPPER=false
    username: admin
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console:
      enabled: true

security:
  ignored: /**
  basic:
    enabled: false

logging:
  level:
    org:
      hibernate:
        SQL: debug
